# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 한승제
title: 동양미래대학교 재학생
email: takh1024@m365.dongyang.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#github_username: takhhan

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Section
about_profile_image: images/profile.jpg
about_content: |
  hello world
content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: FESTIVO
        link: https://github.com/takhhan/festivo
        # additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/sproogen/modern-resume-theme
        quote: >
          국내 축제, 행사 정보 사이트
        description: |
          2인 팀 프로젝트

      - layout: top-middle
        title: FITMATE
        link: https://github.com/ghdals/fitmate/tree/main
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/sproogen/modern-resume-theme
        quote: >
          맞춤형 웨이트 트레이닝 프로그램 제안 프로그램
        description: |
          4인 팀 프로젝트 중 프론트엔드

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Front End
        quote: >
          # Solving 21st century problems by digging holes and making game changing products like the *not a flamethrower*
        description: |
          React, HTML5/CSS

      - layout: left
        title: Back End
        quote: >
          # Solving 21st century problems by digging holes and making game changing products like the *not a flamethrower*
        description: |
          Spring boot, 실시간 채팅 서버, 데이터 크롤링/분석 시스템

      - layout: left
        title: DB
        quote: >
          # Solving 21st century problems by digging holes and making game changing products like the *not a flamethrower*
        description: |
          MySQL

  - title: Education
    layout: list
    content:
      - layout: left
        title: 동양미래대학교
        caption: 2023 - 2026
        sub_title: 컴퓨터소프트웨어
        quote: >
          ?
        description: |
          아직 재학 중

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
